Support custom CN when no PASSWORD is defined
Prior to this change, a custom CN would not work if PASSWORD was
omitted.

Remove verify-pkcs12 target which only existed in the basic profile and
didn't work:

    $ gmake verify-pkcs12 PASSWORD=foo

    python3 profile.py verify-pkcs12 --password "foo"
    Will verify generated PKCS12 certificate stores...
    Will verify client PKCS12 store
    Traceback (most recent call last):
      File "profile.py", line 71, in <module>
        cli.run(commands)
      File "../tls_gen/cli.py", line 55, in run
        dispatch_command(commands, parser, args, options)
      File "../tls_gen/cli.py", line 34, in dispatch_command
        fn(options)
      File "profile.py", line 47, in verify_pkcs12
        verify.verify_pkcs12_store("client", opts)
      File "../tls_gen/verify.py", line 31, in verify_pkcs12_store
        "-keystore", leaf_pkcs12_key_store_path(peer),
    NameError: name 'leaf_pkcs12_key_store_path' is not defined
    gmake: *** [Makefile:56: verify-pkcs12] Error 1

Signed-off-by: Gerhard Lazu <gerhard@rabbitmq.com>